<?php
/**
 * TL_ROOT/system/modules/randomarticle/languages/nl/modules.php 
 * 
 * TYPOlight extension: randomarticle 1.3.1 stable 
 * Dutch translation file 
 * 
 * Copyright : © 2008-2009 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['randomarticle']['0'] = "Willekeurig Artikel";
$GLOBALS['TL_LANG']['FMD']['randomarticle']['1'] = "Toont een willekeurig artikel van een bepaalde pagina als module.";
$GLOBALS['TL_LANG']['MOD']['randomarticle']['0'] = "Willekeurig Artikel";
 
?>
