<?php
/**
 * TL_ROOT/system/modules/randomarticle/languages/nl/tl_module.php 
 * 
 * TYPOlight extension: randomarticle 1.3.1 stable 
 * Dutch translation file 
 * 
 * Copyright : © 2008-2009 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['randomArticle']['0'] = "Wijze van presentatie";
$GLOBALS['TL_LANG']['tl_module']['randomArticle']['1'] = "Deze instelling geldt per module en per bezoeker.";
$GLOBALS['TL_LANG']['tl_module']['keepArticle']['0'] = "Behoud artikel";
$GLOBALS['TL_LANG']['tl_module']['keepArticle']['1'] = "Geef aan hoeveel pageloads hetzelfde artikel getoont moet worden.";
$GLOBALS['TL_LANG']['tl_module']['showTeaser']['0'] = "Toon teaser";
$GLOBALS['TL_LANG']['tl_module']['showTeaser']['1'] = "Toon de aankeiler in plaats van het artikel zelf, gevolgd door de \"Lees meer...\" link.";
$GLOBALS['TL_LANG']['tl_module']['randomArticle_ref'][''] = "Toon een nieuw willekeurig artikel bij elke pageload";
$GLOBALS['TL_LANG']['tl_module']['randomArticle_ref']['1'] = "Toon hetzelfde artikel een bepaald aantal pageloads";
$GLOBALS['TL_LANG']['tl_module']['randomArticle_ref']['2'] = "Toon hetzelfde artikel tijdens een hele bezoekerssessie";
 
?>
